### ISSUE TITLE
go-torch thinks application is doing nothing

### ISSUE THREAD

**Issue by imcom** [uber/go-torch#24] opened 2015-07-29 07:42 UTC
```
imcom@imcom-ubuntu:~/appgw$ go-torch --url "http://localhost:8081" -s "/perf/profile" --binaryname build/apps/appgwd -t "60" -f "torch.svg"
INFO[0000] Profiling ...
FATA[0060] Your application is not doing anything right now. Please try again.
```

I keep getting this error message, but `go tool pprof` works well on the same entry point.

Besides, when I generate flamegraph from the binary output from pprof, there is an error occurred while rendering the flamegraph ...

Is there anything that I am missing?

**Comment by sandlerben** [comment] 2015-07-29 15:54
@imcom I think this is a duplicate of issue #20. 

Also, the binaryname flag is not needed when you profile from your application's pprof endpoint.

**Closed by sandlerben** 2015-07-29 15:54 UTC
